### ISSUE TITLE
partialschur finds only one of three degenerate eigenvectors

### ISSUE THREAD

**Issue by jlbosse** [JuliaLinearAlgebra/ArnoldiMethod.jl#112]
I have  matrix with a three-fold degenerate extremal eigenvalue and `ArnoldiMethod.partialschur` finds only one of them while e.g. `Arpack.eigs` finds all three. See the following MWE:

```julia
using Arpack
using ArnoldiMethod
using SparseArrays

ham_sparse = sparse(I, J, V)     # the numerical values for I, J and V are hosted at https://justpaste.it/5naju

λ, φ = Arpack.eigs(ham_sparse, which=:SR)
print(real(λ))

decomp, _ = partialschur(ham_sparse, nev=6, which=SR())
λ, φ = partialeigen(decomp)
print(real(λ))
```

prints

```raw
[-4.785165067232189, -4.785165067232181, -4.785165067232169, -4.458749101599544, -3.5927605849611726, -3.5927605849611552]
[-4.785165067232141, -4.603267050112509, -4.4587491015995315, -3.59276058496115, -3.502637833700079, -3.2498680277756797]
```

**Comment by PetrKryslUCSD** [comment]
Is this still happening? I also have a problem with multiple repeated eigenvalues, and failure is sometimes observed.

**Comment by RalphAS** [comment]
I get 2 out of 3 with default settings for the current version, but all 3 with `maxdim=40`.  Even Arpack needs a padded subspace to get the next multiplet right (I haven't got all of those with ArnoldiMethod yet).

**Comment by haampie** [comment]
@Jutho did you every look into restart issues with repeated/multiple/tightly clustered eigenvalues in IRA / Krylov-Schur?

**Comment by Jutho** [comment]
Maybe I should revise the docs as this description sounds a bit too optimistic. I think that in general, it is very finicky to rely on numerical noise to generate you the new linearly independent eigenvectors that are not present in the initial starting vector.

With the default values for KrylovKit.eigsolve (`krylovdim=30, maxiter=100`) and randomly generated initial vectors, it seems to find the correct first 6 eigenvalues with degeneracies (typically in 7 iterations = approximately 100 matrix vector products)

But something is strange with the ArnoldiMethod results reported above. It is not that it just does not find 3 linearly independent eigenvectors and thus reports higher lying eigenvalues. The second value it reports is not a correct eigenvalues for this matrix. I think this may point towards a bug.

**Comment by RalphAS** [comment]
This may account for the problem seen here: ISTM that the re-sorting of Ritz values in `_partialschur` should start at index `active` rather than 1, so as not to mix locked subspace content into the working set, or _vice versa_.

**Comment by haampie** [comment]
@RalphAS I think that might be an issue yes. So, a repeated eigenpair converges later than others, and then gets inserted somewhere between already locked vectors, whereas typically eigenpairs converge in order

However, completely at the end, reordering the schur form should still work.

Will have a look.

**Comment by haampie** [comment]
Looks like #116 resolves the issue, but I don't immediately see why.

**Comment by PetrKryslUCSD** [comment]
I'm afraid the change did not fix things at my end.

**Comment by haampie** [comment]
@RalphAS thanks for pointing me somewhat in the right direction. In the end though, sorting only the active part is incorrect, as the algorithm would return the first eigenvalues that converged, instead of the _best_ eigenvalues it can detect over time. For most applications that coincides (dominant eigenvalues converge first), but with repeated eigenvalues that was not the case: they start to converge rather late, sometimes by accident, and at that point you better toss out an already converged eigenvalue further from the target, do a couple more iterations and let the repeated eigenvalue closer to the target converge.

PR #116 implements a double bug fix for purging of converged, unwanted Schur vectors.

On top of that, I noticed there that this package's `partialeigen` may unnecessarily destroy orthogonality of Schur vectors for symmetric matrices, even though `partialeigen` should be a no-op for those as it should coincide with the Schur decomp. I think I'll just document this, although I could make a ::Diagonal/::Hermitian wrapper for `partialeigen` too.

**Comment by haampie** [comment]
One thing I'm not 100% sure about is:

My implementation of purging retains converged vectors in the search subspace, they're simply at index > number of requested eigenvalues

I think Arpack may actually completely remove them from the search subspace: put them at index > mindim and they're automatically truncated.

The latter gives more space for new eigenvectors to converge.

But is that helpful at all? I'm pretty sure the vector you completely toss out starts to converge immediately again, whereas by keeping it in the subspace its deflated.

**Comment by PetrKryslUCSD** [comment]
That is an interesting comparison.

**Comment by haampie** [comment]
In the end purging was implemented to actually remove the converged & wanted vecs, because they may cause stability issues in the Krylov-Schur restart due to tiny residuals.

After they're removed, they may reappear due to rounding noise, but that's better than loss of precision at restart.
